### ISSUE TITLE
Include `_meta_` in export for root package and single document

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/data-modelling-storage-service#286]

**Comment by eoaksnes** [comment]
Use _meta_ from parents if single or subpackage, for root package keep as the original.

**Comment by eoaksnes** [comment]
This package entity should be exported to disc: https://github.com/equinor/dm-cli/blob/74720793df8224b3226e6d6e6a9bab2de314faf8/dm_cli/import_package.py#L280
