### ISSUE TITLE
feat: default attribute should be of type Any

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/data-modelling-storage-service#365]
BlueprintAttribute.json defines the attribute "default" to have `"attributeType": "string"`. This means that if we have an attribute with `"attributeType": "boolean"`, the tests will fail if we set `"default": false`

**Comment by l3abak** [comment]
As we discussed, here is a suggestion for fixing the problem. 

The "attributeType" of "default" attribute in "BlueprintAttribute" should be set to "any", so it can be filled with whatever input. 
Then validating any instance of "BlueprintAttribute" correctly identifies that "any" entry is valid for the attribute "default".
We can call this validation function "EntityValidation". 

* "EntityValidation" recieves a "Blueprint" and its "Entity" and ensures that the two are compatible. For example, 
- type of attributes in Entity is compatible with "attributeType" in Blueprint,
- "optional" and "containment" is correctly implemented. 

The "EntityValidation" function also allows for "minimal" or "strict" mode of operations. 
- "minimal": ignores existing of additional elements in "Entity" and ensures "at minimum" the requires elements in "Blueprint" are correctly presented in "Entity".
- "strict": validation fails if not all specifications in "Blueprint" are exactly followed in "Entity"

* A separate validation function could be seen as "BlueprintValidation". Here a "Blueprint" is validated against itself. In particular the expectation that the entry for "default" attribute should have the same type as the neighbour-attribute "attributeType". 
Another validation point could be, checking if all references types are available.  

It is possible to merge these too function into one by introducing an "if" statement which changes the behaviour. For example, 
`if (entity.type == "BlueprintAttribute") `
`       check-default-type-against-attributeType`

I am not sure which one is better.

**Comment by l3abak** [comment]
Overall, we should be careful not to over-do validation. The most important function for this, at this point, is for plugins to ensure the received entities satisfy the minimum requirements.

**Comment by eoaksnes** [comment]
This should be the attribute definition:

```
{
      "name": "default",
      "attributeType": "dmss://system/SIMOS/Any",
      "type": "dmss://system/SIMOS/BlueprintAttribute",
      "optional": true
    },
```
