### ISSUE TITLE
feat(dm-core-plugins): develop a generic UI Plugin for controlling jobs

### ISSUE THREAD

**Issue by l3abak** [equinor/data-modelling-storage-service#382]
The process of starting, stopping, fetching results, and logs is relatively generic. 
It should be possible to develop a generic UI Plugin for jobs, which with some configuration, would be able to provide a decent view.

**Comment by KristianKjerstad** [comment]
description of CreateJobEntity component:


- can use a default job input entity. in this case, the dmss api will be called and uploads the default entity.
- - can either upload job entity to a package OR to an uncontained attribute in a document or a contained attribute in a document.
- if default job input entity is not provided, the form plugin is used to render input fields the user can use to build a job entity. 
- - the job entity can either be uploaded to a package OR  to an uncontained attribute in a document or a contained attribute in a document.

**Comment by eoaksnes** [comment]
* Plugin 1: List of jobs
* Plugin 2: Single job
