### ISSUE TITLE
refactor: reduce/merge number of endpoints

### ISSUE THREAD

**Issue by eoaksnes** [equinor/data-modelling-storage-service#414]
- [x] Merge document get by id and get by path @eoaksnes 
- [x] Change delete endpoint @eoaksnes (@soofstad)
  - [x]  Is it possible to delete things with format [[1,2],[3,4]] @ingeridhellen 
- [x] Merg document add endpoints @eoaksnes (@KristianKjerstad)  https://github.com/equinor/data-modelling-storage-service/pull/430
- [x] use new reference format for endpoints in export_feature.py @KristianKjerstad  https://github.com/equinor/data-modelling-storage-service/pull/441

**Comment by KristianKjerstad** [comment]
Question regarding Merge document add endpoint:


Example: we want to add a document to a root package with id 100. Assume the root package has 6 documents initially.


Example of valid requests are:
`POST localhost:5000/api/documents/data-source-name/$100`
`POST localhost:5000/api/documents/data-source-name/root_package`

However, should we also support  adding document using the `.attribute` syntax?
`POST localhost:5000/api/documents/data-source-name/root_package.content[6]`

**Comment by soofstad** [comment]
Been a small discussion on this already.

IMO, the last request should be done as an "update()", that endpoint handles non-existing items/attributes.
Adding only makes sense in context of a list.

@ingeridhellen proposed we change "add()" to "insert(index=-1)" and I think that could be a good idea.

Question: Is there any scenario where you need to "add()" NOT to a list, and can't use "update()"?

**Comment by KristianKjerstad** [comment]
okay, cool!

It makes sense to use "update" instead in the last request.

I can't think of any scenario where we need to add not to a list and can't use update

**Comment by KristianKjerstad** [comment]
from discussion, it was concluded that the export endpoints should only handle reference on path format.
