### ISSUE TITLE
fix(dmss, dm-cli): package content should be storage non-contained and model contained

### ISSUE THREAD

**Issue by eoaksnes** [equinor/data-modelling-storage-service#458]
Tasks:
- [x] 1) Update the `Package` blueprint, and set the `content` attribute to contained (model contained). 2) Change so that references of type `storage` is not resolved by default. Make sure that what to resolve is controlled by the depth, default is 0.  @eoaksnes https://github.com/equinor/data-modelling-storage-service/pull/464
- [x] Update DM CLI to insert documents and packages inside another package to reference type storage @eoaksnes https://github.com/equinor/dm-cli/pull/106

Storage recipes:

> **_NOTE:_** Make sure that the storage recipe for the `Package` blueprint that says that the content attribute is storage non-contained is loaded using DM CLI. To verify that it works, create a new package using Explorer, and check that the reference type is of type `storage´. The [storage recipe](https://github.com/equinor/data-modelling-storage-service/blob/master/src/home/system/SIMOS/recipe_links/package.json) says that the content should be storage non-contained.

Binary data:

> **_NOTE:_** The binary data should never be resolved automatically and instead one should use the `/blobs` endpoint.

**Comment by KristianKjerstad** [comment]
does not contain enough info to start on this task....

It is not documented how the storage uncontained feature is supposed to work.

**Comment by KristianKjerstad** [comment]
- "Update DM CLI to insert documents and packages inside another package to reference type storage" - don't understand this sentence.l

**Comment by KristianKjerstad** [comment]
@eoaksnes is this issue done?
