### ISSUE TITLE
fix: update modeling used in employeeapp - content should be storage reference, not link reference

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/data-modelling-storage-service#484]
mut be updated both in dmss (blueprint) and in typing in dm-core-packges

**Comment by eoaksnes** [comment]
it should be storage, since if delete file the content (binary) should be deleted

**Comment by KristianKjerstad** [comment]
correct look


![Image](https://github.com/equinor/data-modelling-storage-service/assets/69512295/c93a635c-0479-4cf5-a70f-11f75dc8754d)



--


![Image](https://github.com/equinor/data-modelling-storage-service/assets/69512295/8e62e460-85aa-4de4-9192-9e16faa6c350)

----


![Image](https://github.com/equinor/data-modelling-storage-service/assets/69512295/b755be1c-f791-488b-bd67-e09239a47ee7)

**Comment by KristianKjerstad** [comment]
not needed, better to create a new example app
