### ISSUE TITLE
fix: adding optional object expects object to already exist

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/data-modelling-storage-service#485]
Found endpoints affected, but it may be more:
- documentAdd @eoaksnes 

If you have a blueprint with an optional attribute myOptionalAttribute, an entity of that blueprint does not have to include myOptionalAttribute at all. However, if you try to add a document or reference to that attribute, you get an error.

- [x] fix bug in add() for document_service.py https://github.com/equinor/data-modelling-storage-service/pull/497

**Comment by KristianKjerstad** [comment]
wait until document service refactor is done (move functionality out to use cases)
