### ISSUE TITLE
fix: make resolve_blueprint_use_case check that $id is an uid4

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/data-modelling-storage-service#596]
> There are one bug, and one possible feature request:
> 
> 1. Fix: If you pass in the address DemoDataSource/$UncontainedObject, it will raise an ApplicationException. This is due to L37, which has a case sensitive regex that only allows ids to have lower case letters and numbers
> 2. Feat: Ideally, you should be able to obtain the blueprint of any complex attribute too, for example DemoDataSource/$UncontainedObject.employees

**Comment by collinlokken** [comment]
Conclusion: we will only allow uidv4 for ids
