### ISSUE TITLE
ci(dmss): publish DMSS API package to PyPI fails

### ISSUE THREAD

**Issue by soofstad** [equinor/data-modelling-storage-service#681]
Just turn off publish in the workflow. Maybe not delete the code, but just turn it off.

**Comment by soofstad** [comment]
It has been decided that we should no longer publish the generated package. It's easy enough to create yourself. As we are doing in DM-CLI and Job-api.

Has this changed?

**Comment by eoaksnes** [comment]
@soofstad  If we release a new DMSS version, the CI tries to publish a new package to PyPI:

![Image](https://github.com/equinor/data-modelling-storage-service/assets/1190419/5e52fbf6-54b9-41af-9331-71039e2c1cd7)

I also remember that we decided to not use this package inside our services, but could it be beneficial to have it available to others?  If we decide not to publish (support) this package, we should remove the code.
