### ISSUE TITLE
feat: add label, dataSources, adminRoles, and roles to the application blueprint

### ISSUE THREAD

**Issue by pbullhove** [equinor/data-modelling-storage-service#695]
Let's add these attributes to CORE:Application as optional attributes.
{
      "name": "label",
      "type": "CORE:BlueprintAttribute",
      "attributeType": "string",
      "optional": true
    },
    {
      "name": "dataSources",
      "type": "CORE:BlueprintAttribute",
      "attributeType": "string",
      "dimensions": "*",
      "optional": true
    },
    {
      "name": "adminRole",
      "type": "CORE:BlueprintAttribute",
      "attributeType": "string",
      "optional": true
    },
    {
      "name": "roles",
      "type": "CORE:BlueprintAttribute",
      "attributeType": "string",
      "dimensions": "*",
      "optional": true
    }

**Comment by l3abak** [comment]
We decided to have "roles" defined in the Header plugin instead. That will be just a mapping between available Azure roles, and a caption and description. 

Please check where "dataSources" is used besides explorer plugin. If it is just there, I would argue that it should be moved to the Explorer plugin config in UI recipe. 

Then only label should be added to Application.

**Comment by eoaksnes** [comment]
- [ ] Add Role blueprint that contains the attributes: type, name, label, remoteRoleName
- [ ] Add a list of roles to the Application blueprint
- [ ] Use the roles added to the Application blueprint in the header plugin
- [ ] Remote the roles:[] in the header plugin.
